# Date: Nov 22, 2025
# Name: ICE4.py - Lab 4
# Programmers:  Alyssa & Lucas
# Description: Using Selenium framework and WebDriver to test Body Fat Calculator web application



# Generated by Selenium IDE
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Lab4TestCase(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()
        cls.driver.maximize_window()
        time.sleep(2) # wait for opening

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def setUp(self):
        self.driver.get("https://www.calculator.net/body-fat-calculator.html")

    def test_01validgender(self):
        gender = "male" #Change this (male or female)
        if gender == "male":
            # Male test with metric units
            self.driver.find_element(By.NAME, "cage").click()
            self.driver.find_element(By.NAME, "cage").clear()
            self.driver.find_element(By.NAME, "cage").send_keys("15")
            self.driver.find_element(By.NAME, "cweightkgs").click()
            self.driver.find_element(By.NAME, "cweightkgs").clear()
            self.driver.find_element(By.NAME, "cweightkgs").send_keys("220")
            self.driver.find_element(By.ID, "cheightmeter").click()
            self.driver.find_element(By.ID, "cheightmeter").click()
            element = self.driver.find_element(By.ID, "cheightmeter")
            actions = ActionChains(self.driver)
            actions.double_click(element).perform()
            self.driver.find_element(By.ID, "cheightmeter").click()
            self.driver.find_element(By.ID, "cheightmeter").clear()
            self.driver.find_element(By.ID, "cheightmeter").send_keys("90")
            self.driver.find_element(By.ID, "cneckmeter").click()
            self.driver.find_element(By.ID, "cneckmeter").click()
            element = self.driver.find_element(By.ID, "cneckmeter")
            actions = ActionChains(self.driver)
            actions.double_click(element).perform()
            self.driver.find_element(By.ID, "cneckmeter").click()
            self.driver.find_element(By.ID, "cneckmeter").clear()
            self.driver.find_element(By.ID, "cneckmeter").send_keys("18")
            self.driver.find_element(By.ID, "cwaistmeter").click()
            self.driver.find_element(By.ID, "cwaistmeter").click()
            element = self.driver.find_element(By.ID, "cwaistmeter")
            actions = ActionChains(self.driver)
            actions.double_click(element).perform()
            self.driver.find_element(By.ID, "cwaistmeter").click()
            self.driver.find_element(By.ID, "cwaistmeter").clear()
            self.driver.find_element(By.ID, "cwaistmeter").send_keys("100")
            self.driver.find_element(By.NAME, "x").click()
            self.driver.find_element(By.CSS_SELECTOR, ".rightresult").click()
            self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
            self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
            element = self.driver.find_element(By.CSS_SELECTOR, "font > b")
            actions = ActionChains(self.driver)
            actions.double_click(element).perform()
            result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
            assert result.text == "Body Fat: 60.7%"
            print(f"Male metric test completed successfully. Result: {result.text}")
            self.driver.find_element(By.CSS_SELECTOR, "#right > div:nth-child(1)").click()
        else:
            # Female test with imperial units
            self.driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2)").click()
            self.driver.find_element(By.LINK_TEXT, "US Units").click()
            self.driver.find_element(By.NAME, "cage").clear()
            self.driver.find_element(By.NAME, "cage").send_keys("40")
            self.driver.find_element(By.ID, "content").click()
            self.driver.find_element(By.NAME, "cweightlbs").clear()
            self.driver.find_element(By.NAME, "cweightlbs").send_keys("220.46")
            self.driver.find_element(By.ID, "cheightfeet").clear()
            self.driver.find_element(By.ID, "cheightfeet").send_keys("6")
            element = self.driver.find_element(By.ID, "cheightfeet")
            actions = ActionChains(self.driver)
            actions.move_to_element(element).click_and_hold().perform()
            element = self.driver.find_element(By.ID, "cheightfeet")
            actions = ActionChains(self.driver)
            actions.move_to_element(element).perform()
            element = self.driver.find_element(By.ID, "cheightfeet")
            actions = ActionChains(self.driver)
            actions.move_to_element(element).release().perform()
            self.driver.find_element(By.ID, "cheightinch").clear()
            self.driver.find_element(By.ID, "cheightinch").send_keys("2")
            self.driver.find_element(By.ID, "cneckfeet").clear()
            self.driver.find_element(By.ID, "cneckfeet").send_keys("0")
            self.driver.find_element(By.ID, "cneckinch").clear()
            self.driver.find_element(By.ID, "cneckinch").send_keys("22.44")
            self.driver.find_element(By.CSS_SELECTOR, "body").click()
            self.driver.find_element(By.ID, "cwaistfeet").clear()
            self.driver.find_element(By.ID, "cwaistfeet").send_keys("0")
            self.driver.find_element(By.ID, "cwaistinch").clear()
            self.driver.find_element(By.ID, "cwaistinch").send_keys("38.58")
            self.driver.find_element(By.ID, "chipfeet").clear()
            self.driver.find_element(By.ID, "chipfeet").send_keys("0")
            self.driver.find_element(By.ID, "chipinch").click()
            self.driver.find_element(By.ID, "chipinch").click()
            self.driver.find_element(By.ID, "chipinch").click()
            element = self.driver.find_element(By.ID, "chipinch")
            actions = ActionChains(self.driver)
            actions.double_click(element).perform()
            self.driver.find_element(By.ID, "chipinch").clear()
            self.driver.find_element(By.ID, "chipinch").send_keys("39.37")
            self.driver.find_element(By.NAME, "x").click()
            self.driver.find_element(By.CSS_SELECTOR, ".verybigtext").click()
            result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
            assert result.text == "Body Fat: 23.2%"
            print(f"Female imperial test completed successfully. Result: {result.text}")

    def test_02invalidnegativemetric(self):
        self.driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(2) > .rbmark").click()
        self.driver.find_element(By.NAME, "cage").clear()
        self.driver.find_element(By.NAME, "cage").send_keys("-1")
        self.driver.find_element(By.NAME, "cweightkgs").clear()
        self.driver.find_element(By.NAME, "cweightkgs").send_keys("-1")
        self.driver.find_element(By.CSS_SELECTOR, ".panel2").click()
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("-1")
        self.driver.find_element(By.ID, "cneckmeter").clear()
        self.driver.find_element(By.ID, "cneckmeter").send_keys("-1")
        self.driver.find_element(By.ID, "cwaistmeter").clear()
        self.driver.find_element(By.ID, "cwaistmeter").send_keys("-1")
        self.driver.find_element(By.ID, "chipmeter").clear()
        self.driver.find_element(By.ID, "chipmeter").send_keys("-1")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.CSS_SELECTOR, ".rightresult > div").click()
        self.driver.find_element(By.CSS_SELECTOR, ".rightresult > div").click()
        result = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font")
        assert result.text == "Waist need to be numeric."
        print(f"Invalid negative metric test completed successfully. Result: {result.text}")

    def test_03invaliddatatypesmetric(self):
        self.driver.find_element(By.CSS_SELECTOR, ".cbcontainer:nth-child(1) > .rbmark").click()
        self.driver.find_element(By.ID, "metricheightweight").click()
        time.sleep(0.3)  # Wait for unit switch
        self.driver.find_element(By.ID, "content").click()
        self.driver.find_element(By.NAME, "cage").clear()
        self.driver.find_element(By.NAME, "cage").send_keys("s")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for validation
        self.driver.find_element(By.NAME, "cweightkgs").clear()
        self.driver.find_element(By.NAME, "cweightkgs").send_keys("xx")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for validation
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("[1]")
        self.driver.find_element(By.ID, "cneckmeter").clear()
        self.driver.find_element(By.ID, "cneckmeter").send_keys("true")
        self.driver.find_element(By.ID, "cwaistmeter").click()
        self.driver.find_element(By.ID, "cwaistmeter").click()
        element = self.driver.find_element(By.ID, "cwaistmeter")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "cwaistmeter").click()
        self.driver.find_element(By.ID, "cwaistmeter").clear()
        self.driver.find_element(By.ID, "cwaistmeter").send_keys("x")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for page update
        
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("z")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for validation
        
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("-1")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for validation
        
        self.driver.find_element(By.ID, "cheightmeter").clear()
        self.driver.find_element(By.ID, "cheightmeter").send_keys("a")
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.3)  # Wait for validation
        
        self.driver.find_element(By.ID, "cneckmeter").clear()
        self.driver.find_element(By.ID, "cneckmeter").send_keys("[1]")
        time.sleep(0.5)  # Wait for field update
        
        self.driver.find_element(By.NAME, "x").click()
        time.sleep(0.5)  # Wait for validation
        
        self.driver.find_element(By.CSS_SELECTOR, ".rightresult > div").click()
        result = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > font")
        assert result.text == "Please provide a positive weight."
        print(f"Invalid data types metric test completed successfully. Result: {result.text}")

    def test_04validemtpyinches(self):
        self.driver.find_element(By.LINK_TEXT, "US Units").click()
        self.driver.find_element(By.ID, "cheightinch").clear()
        self.driver.find_element(By.ID, "cheightinch").send_keys("0")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.ID, "cheightfeet").clear()
        self.driver.find_element(By.ID, "cheightfeet").send_keys("0")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.ID, "cheightfeet").clear()
        self.driver.find_element(By.ID, "cheightfeet").send_keys("6")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.ID, "cneckinch").clear()
        self.driver.find_element(By.ID, "cneckinch").send_keys("0")
        self.driver.find_element(By.ID, "cwaistinch").clear()
        self.driver.find_element(By.ID, "cwaistinch").send_keys("0")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
        self.driver.find_element(By.CSS_SELECTOR, ".verybigtext").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".verybigtext")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
        assert result.text == "Body Fat: 25.3%"
        print(f"Valid empty inches test completed successfully. Result: {result.text}")

    def test_05BoundaryMaxHeight(self):
        self.driver.find_element(By.LINK_TEXT, "US Units").click()
        self.driver.find_element(By.ID, "cheightfeet").clear()
        self.driver.find_element(By.ID, "cheightfeet").send_keys("99999")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
        result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
        assert result.text == "Body Fat: 0.0%"
        print(f"Boundary max height test completed successfully. Result: {result.text}")

    def test_06BoundaryMinHeight(self):
        self.driver.find_element(By.LINK_TEXT, "US Units").click()
        self.driver.find_element(By.ID, "cheightfeet").clear()
        self.driver.find_element(By.ID, "cheightfeet").send_keys("0.00001")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.CSS_SELECTOR, ".verybigtext").click()
        result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
        assert result.text == "Body Fat: 78.8%"
        print(f"Boundary min height test completed successfully. Result: {result.text}")

    def test_07errorzeroweight(self):
        self.driver.find_element(By.NAME, "cweightkgs").clear()
        self.driver.find_element(By.NAME, "cweightkgs").send_keys("0")
        self.driver.find_element(By.NAME, "x").click()
        self.driver.find_element(By.CSS_SELECTOR, ".verybigtext").click()
        result = self.driver.find_element(By.CSS_SELECTOR, "font > b")
        assert result.text == "Body Fat: 15.7%"
        print(f"Zero weight test completed successfully. Result: {result.text}")
